-- AlterTable
ALTER TABLE "User" ADD COLUMN "age" INTEGER;
ALTER TABLE "User" ADD COLUMN "fitnessGoal" TEXT;
ALTER TABLE "User" ADD COLUMN "gender" TEXT;
ALTER TABLE "User" ADD COLUMN "height" REAL;
ALTER TABLE "User" ADD COLUMN "trainingDays" TEXT;
ALTER TABLE "User" ADD COLUMN "weight" REAL;
